services:
  app:
    build: .
    ports:
      - '10101:10101'
    volumes:
      - ./txs.json:/app/txs.json
      - ./notifications.json:/app/notifications.json
      - ./log.txt:/app/log.txt
      - ./error.txt:/app/error.txt
    restart: always
    environment:
      - NODE_ENV=production