services:
  app:
    build: .
    container_name: klein-server-listener
    ports:
      - '10101:10101'
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - NODE_ENV=production