services:
  app:
    build: .
    container_name: klein-server-listener
    ports:
      - '10101:10101'
    volumes:
      - ./data:/app/data
      - klein-node-volume:/app/klein-node-volume
    restart: always
    environment:
      - NODE_ENV=production
volumes:
  klein-node-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/klein-node-volume